name: Matrix demo
on: 
  push:
    branches:
      - master
job: 
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build the code
        run: npm run build
