name: Reusable workflow
on: 
  workflow_call:
    inputs:
      artifact_name:
        description: The name of the deployable artifacts
        required: false
        default: dist
        type: string
   # secrets:  
    #  some-secret:
    #    required: false
    output:
      result:
        description: The result of deployment operation
        value: ${{ jobs.deploy.outputs.outcome}}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.step-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Downloading the files
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: List files
        run: ls          
      - name: Log deployment message
        run: echo "Deploying feature..."
      - name: Set result output
        id: step-result
        run: echo "step-result == 'success'" >> GITHUB_OUTPUT  